# Generated by Django 4.1.1 on 2023-05-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_location',
            field=models.CharField(default='United States', max_length=100),
        ),
    ]
