# Generated by Django 4.1.1 on 2023-05-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0002_jobpost_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobnotification',
            name='interview_time',
            field=models.CharField(default='uncheck', max_length=50),
        ),
    ]
