# Generated by Django 4.1.1 on 2023-05-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0005_experience_experience_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='interview_location_url',
            field=models.CharField(max_length=1000),
        ),
    ]
