# Generated by Django 4.1.1 on 2023-05-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0006_alter_application_interview_location_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_pay',
            field=models.CharField(default='', max_length=200),
        ),
    ]
