# Generated by Django 4.1.1 on 2023-05-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0008_chat_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='latest_update',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
