# Generated by Django 4.1.1 on 2023-06-01 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0009_chat_latest_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userPassword',
            field=models.CharField(default='no_active_password', max_length=500),
        ),
        migrations.CreateModel(
            name='ChatReported',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_reported', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workapp.chat')),
                ('reporting_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='report_sender', to='workapp.profile')),
            ],
        ),
    ]
