# Generated by Django 4.1.1 on 2023-06-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0010_profile_userpassword_chatreported'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chatreported',
            table='Chat Reported',
        ),
    ]
