# Generated by Django 4.1.1 on 2023-06-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0011_alter_chatreported_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admin_conversation',
            field=models.CharField(default='none', max_length=500),
        ),
    ]
