# Generated by Django 4.1.1 on 2023-06-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0012_profile_admin_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userDOB',
            field=models.CharField(default='-- -- --', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='userGender',
            field=models.CharField(default='Male', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='userLocation',
            field=models.CharField(default='-- -- --', max_length=100),
        ),
    ]
