# Generated by Django 4.1.1 on 2023-06-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0013_profile_userdob_profile_usergender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_external',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_external_link',
            field=models.CharField(default='___', max_length=5000),
        ),
    ]
